version: 2
jobs:
  fetch_csv:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout:
          path: ~/repo
      - add_ssh_keys:
          fingerprints:
            - "7f:97:d9:ea:aa:94:0d:01:56:a4:62:26:b3:3d:8e:17"
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Build CSV
          command: |
            . venv/bin/activate
            python main.py
      - run:
          name: Set Git identity
          command: |
            git config --global user.email "robot@circleci.com"
            git config --global user.name "CircleCI"
      - run:
          name: Push to GitHub
          command: |
            cd ~/repo
            if [ -n "$(git status --porcelain)" ]; then
              git add data
              git commit -m "New data at $(date -u +'%Y-%m-%dT%H:%M:%SZ') [skip ci]"
              git push origin master
            else
              echo "No changes";
            fi

workflows:
  version: 2
  fetch_and_push:
    jobs:
      - fetch_csv
  cron:
    triggers:
      - schedule:
          cron: "10 7 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - fetch_csv
